[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Arxys Video X v3 Documentation"
authors = [{name = "Arxys Support Team", email = "support@arxys.com"}]
dynamic = ["version", "description"]
